version: '3'
services:
  app:
    image: app
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/tmp
      - /root/async-profiler:/root/async-profiler
    security_opt:
      - seccomp:unconfined
    environment:
      - MY_ARGS=-XX:+PreserveFramePointer -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints
